project_id = "dpxuacnrncwyopehwxsj"

[functions.binance-portfolio]
verify_jwt = false

[functions.analyze-portfolio]
verify_jwt = false

[functions.suggest-coins]
verify_jwt = false

[functions.enrich-coin]
verify_jwt = false

[functions.margin-buy]
verify_jwt = false

[functions.margin-transfer]
verify_jwt = false

[functions.margin-borrow]
verify_jwt = false

[functions.margin-order]
verify_jwt = false
